- assets/bibs/Chemnitz.json
- src/de/geeksfactory/opacclient/apis/TouchPoint.java
Only feature not supported yet (because not available in Chemnitz): Cancelling reservations
> Account support for TouchPoint

- src/de/geeksfactory/opacclient/apis/IOpac.java
The wrong detail page was shown when selecting media on the second page and after.
> Bugfix for iOpac

- src/de/geeksfactory/opacclient/apis/Pica.java
- Sometimes multiple copies were accidentally merged into one
- Return date will now be parsed correctly
> Improve parsing of copies for Pica

- opacclient/opacapp/src/main/res/layout/activity_main_twopane.xml
needed for Plus Edition compatibility
> Update with latest commits from master

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Adis.java
> fix single "Vormerkung" in Adis

- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountFragment.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/MultiStepResultHelper.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java
> fix MultiStepResultHelper AsyncTasks

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/BiBer1992.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Bibliotheca.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Heidi.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/IOpac.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Pica.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SISIS.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/TouchPoint.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Zones22.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AboutFragment.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountFragment.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/LibraryListActivity.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java
- opacclient/opacapp/src/main/res/layout-w720dp/activity_account_list.xml
- opacclient/opacapp/src/main/res/layout-w720dp/fragment_account.xml
- opacclient/opacapp/src/main/res/layout/activity_account_edit.xml
- opacclient/opacapp/src/main/res/layout/activity_account_list.xml
- opacclient/opacapp/src/main/res/layout/activity_suggest_library.xml
- opacclient/opacapp/src/main/res/layout/activity_welcome.xml
- opacclient/opacapp/src/main/res/layout/dialog_about.xml
- opacclient/opacapp/src/main/res/layout/fragment_account.xml
- opacclient/opacapp/src/main/res/layout/listitem_prolongall_result.xml
- opacclient/opacapp/src/main/res/layout/listitem_searchresult_loading.xml
- opacclient/opacapp/src/main/res/layout/listitem_simple.xml
- opacclient/opacapp/src/main/res/values-de/strings.xml
- opacclient/opacapp/src/main/res/values-it/strings.xml
- opacclient/opacapp/src/main/res/values-tr/strings.xml
- opacclient/opacapp/src/main/res/values/strings.xml
This addresses the following issues from #281:
- Remove german acronyms (e.g. "tvEntlHeader")
- Make view IDs meaningful (avoid e.g. "textView1")
> More Code style improvements (#281)

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/IOpac.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/i18n/StringProvider.java
- opacclient/opacapp/src/main/res/values-de/strings_api_errors.xml
- opacclient/opacapp/src/main/res/values/strings_api_errors.xml
including support for prolongAll()
> Make iOPAC API ready for version 1.45 of the OPAC software

- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/MainActivity.java
Including support for NFC data = media ID (like in Schleswig) when there is no barcode search field
> Re-implement NFC search with the new SearchFields

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/BaseApi.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Primo.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/ReadOnlyApi.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SearchOnlyApi.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/VuFind.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WebOpacAt.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WebOpacNet.java
- opacclient/opacapp/src/main/assets/bibs/Axams.json
- opacclient/opacapp/src/main/assets/bibs/Innsbruck.json
- opacclient/opacapp/src/main/assets/bibs/Innsbruck_AK.json
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/OpacClient.java
- opacclient/tests/src/main/java/de/geeksfactory/opacclient/tests/UtilTest.java
- opacclient/tests/src/main/java/de/geeksfactory/opacclient/tests/apitests/LibraryApiTestCases.java
This adds a first implementation plus definition of three libraries in Tyrol, Austria.
I'm happy to hear hints for improvements. :smile:
> Add implementation for web-opac.at API

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WebOpacAt.java
- opacclient/opacapp/src/main/assets/bibs/Axams.json
- opacclient/opacapp/src/main/assets/meanings/web-opac.at.json
While testing, a few issues popped up. I also implemented a meaning translation file …
> WebOpacAt: fixes and improvements

- opacclient/opacapp/src/main/assets/bibs/Mils.json
> Fix Mils.json: add missing information

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Zones.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/utils/ISBNTools.java
- opacclient/opacapp/src/main/assets/bibs/Hannover.json
- opacclient/opacapp/src/main/assets/bibs/Kiel.json
- opacclient/opacapp/src/main/assets/bibs/Koeln.json
- opacclient/opacapp/src/main/assets/bibs/Luebeck.json
- opacclient/opacapp/src/main/assets/meanings/zones.json
- opacclient/opacapp/src/main/assets/meanings/zones22.json
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/OpacClient.java
- opacclient/tests/src/main/java/de/geeksfactory/opacclient/tests/apitests/LibraryApiTestCases.java
- tools/add_library.py
added Libraries: Kiel, Lübeck, Hannover
> Support for Zones 1.8

- opacclient/opacapp/src/main/assets/bibs/Ahlen.json
- opacclient/opacapp/src/main/assets/bibs/Beckum.json
- opacclient/opacapp/src/main/assets/bibs/Beckum_Neubeckum.json
- opacclient/opacapp/src/main/assets/bibs/Kehl.json
- opacclient/opacapp/src/main/assets/bibs/Telgte.json
- opacclient/opacapp/src/main/assets/bibs/Warendorf.json
Ahlen, Beckum, Neubeckum, Telgte, Warendorf (all from bibliothek-im-netz.de), Kehl
> Add libraries

- opacclient/opacapp/src/main/assets/bibs/Muenchen_KSFH.json
- opacclient/opacapp/src/main/assets/bibs/Roth.json
- opacclient/opacapp/src/main/assets/bibs/Schramberg.json
Added: München Katholische Stiftungsfachhochschule, Roth
Fixed: accounttable in Schramberg
> Add and fix libraries

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/PicaLBS.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/BaseTest.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/PicaLBSTest.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/PicaOldTest.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/WinBiapTest.java
- opacclient/libopac/src/test/resources/pica_lbs/medialist/greifswald.html
- opacclient/opacapp/src/main/assets/bibs/Muenchen_IJB.json
- opacclient/opacapp/src/main/assets/bibs/Wettingen.json
The media title was not recognized in Greifswald.
I also added a test for the PicaLBS API using a HTML sample from this library.
> More fixes for PICA LBS (UB Greifswald)

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/IOpac.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WinBiap.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/IOpacTest.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/WinBiapTest.java
- opacclient/libopac/src/test/resources/iopac/heide.html
- opacclient/libopac/src/test/resources/winbiap/medialist/geltendorf.html
WinBiap: Add account compatibility for Version 4.4, using HTML sample from Geltendorf
IOpac: Added Test using HTML sample from Heide, fix a wrong default value
> Fix for WinBiap, and changes for IOpac

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Pica.java
(After I fixed this bug, I forgot to create the corresponding pull request)
> Fix PICA bug for getSearchFields()

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Zones.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/ZonesAccountTest.java
- opacclient/libopac/src/test/resources/zones/medialist/koeln.html
- opacclient/libopac/src/test/resources/zones/reslist/koeln.html
- Add unit test for account view using HTML files from Köln
- Show error messages when prolonging is not possible (previously, an empty dialog would be shown sometimes)
- Add support for link from account to detail view (tested in Köln)
> Improvements for Zones

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WinBiap.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/WinBiapAccountTest.java
- opacclient/libopac/src/test/resources/winbiap/reslist/neufahrn.html
- opacclient/opacapp/src/main/assets/bibs/Dreieich.json
- opacclient/opacapp/src/main/assets/bibs/Ettlingen.json
- opacclient/opacapp/src/main/assets/bibs/Memmingen.json
Added libraries: Dreieich, Memmingen, Ettlingen
Reservations and login should now work correctly with WinBiap 4.3
> Add more libraries, fix WinBiap 4.3

- opacclient/opacapp/src/main/assets/bibs/Ennepetal.json
- opacclient/opacapp/src/main/assets/bibs/Gottmadingen.json
- opacclient/opacapp/src/main/assets/bibs/Langenfeld.json
- opacclient/opacapp/src/main/assets/bibs/Mona_UWI.json
- opacclient/opacapp/src/main/assets/bibs/Stadtbergen.json
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/OpacActivity.java
- Added: Ennepetal, University of the West Indies (Mona), Stadtbergen, Gottmadingen
- Account support for: Langenfeld
- Two adjustments required for compatibility with the Plus Edition
> Add libraries, adjustments for Plus Edition

- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/UtilTest.java
- opacclient/opacapp/src/main/assets/bibs/Oehringen.json
- opacclient/tests/src/main/java/de/geeksfactory/opacclient/tests/apitests/LibraryApiTestCases.java
- opacclient/tests/src/test/java/de/geeksfactory/opacclient/tests/JSONFilesTest.java
- opacclient/tests/src/test/java/de/geeksfactory/opacclient/tests/UtilTest.java
Don't merge this yet, the Travis build should fail...
> Add test for JSON files' validity

- opacclient/opacapp/src/main/assets/bibs/Gladbeck.json
- opacclient/opacapp/src/main/assets/bibs/Marl.json
- Gladbeck: updated accounttable according to screenshot
- Marl: not verified with screenshot, but we received bug reports, it is hosted on the same server and had the same configuration before
> Fix accounttables 

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WinBiap.java
- opacclient/opacapp/src/main/assets/bibs/Dusslingen.json
- One more WinBiap 4.4 fix. This time it doesn't apply to all libraries with this version, but only those that completely removed the `user/login.aspx` page and use the login form on the home page instead.
- Added: Dusslingen
> WinBiap 4.4 fix, Added library

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Open.java
make parse_result protected and use Document instead of HTML
> Open: Plus Edition compatibility

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Open.java
> OPEN: improve search parsing

- opacclient/opacapp/build.gradle
- opacclient/opacapp/src/debug/java/de/geeksfactory/opacclient/utils/DebugTools.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SuggestLibraryActivity.java
- opacclient/opacapp/src/release/java/de/geeksfactory/opacclient/utils/DebugTools.java
> SuggestLibraryActivity: Use OkHttp and Stetho

- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/StarredFragment.java
- opacclient/opacapp/src/main/res/values/strings.xml
Hi,
Below are the changes made for Issue #428.
- I have added a method called showSnackBar()  and added a private variable "sItem" in StarredFragment java class.
- I have added two strings "starred_removed" and "starred_removed_undo" in values folder.[I believe you will handle the localization part]
I have tested the changes and it is working fine. Please let me know if there are any changes to be done.
Thanks,
Sulekha
> Added code to display SnackBar - Issue 428

- .gitlab-ci.yml
- .travis.yml
- opacclient/build.gradle
- opacclient/libopac/build.gradle
- opacclient/opacapp/build.gradle
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/reminder/ReminderHelper.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/reminder/SyncAccountService.java
- opacclient/opacapp/src/test/java/de/geeksfactory/opacclient/reminder/ReminderHelperTest.java
- opacclient/opacapp/src/test/java/de/geeksfactory/opacclient/reminder/SyncAccountServiceTest.java
This addresses #432. Some basic unit tests are already there.
> Add unit tests for ReminderHelper

- opacclient/opacapp/build.gradle
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/utils/PrintUtils.java
- opacclient/opacapp/src/main/res/drawable/ic_print_shop_white_24dp.xml
- opacclient/opacapp/src/main/res/menu/search_result_details_activity.xml
- opacclient/opacapp/src/main/res/raw/print_template.mustache
- opacclient/opacapp/src/main/res/values/strings.xml
Here is my solution to issue #431
> Print details of a search result #431

- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountEditActivity.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountListActivity.java
- opacclient/opacapp/src/main/res/layout/activity_account_edit.xml
- opacclient/opacapp/src/main/res/values-de/strings.xml
- opacclient/opacapp/src/main/res/values/strings.xml
The Text inputs for username and password were labelled as "optional", which caused confusion for some users. Therefore, I added two RadioButtons to select whether the account is anonymous or has credentials. When the former is selected, the two inputs are hidden.
> Improve AccountEditActivity UX

- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/OpacClient.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/storage/PreferenceDataSource.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/webservice/UpdateHandler.java
- opacclient/opacapp/src/test/java/de/geeksfactory/opacclient/webservice/LibraryConfigUpdateServiceTest.java
@johan12345 Asking for review :)
> Be more robust against missing assets when updating the APK

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WinBiap.java
- improve media type detection in account view
- Fix cancelling reservations (error occured e.g. in Neufahrn)
> WinBiap fixes

- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/reminder/ReminderBroadcastReceiver.java
We regularly receive crash reports about DataIntegrityExceptions and don't know what causes them to appear.
This is not the way we *should* fix this problem, but at least this way the exceptions won't cause notifications not to be shown.
> Try to work around DataIntegrityExceptions when showing notifications

- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountEditActivity.java
As in Issue #473 there now is an toggle button for the password if it was not set before.
> Added PasswordToggle in case that Password wasn´t set before. #473

- opacclient/opacapp/build.gradle
- opacclient/opacapp/src/main/AndroidManifest.xml
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/networking/AndroidHttpClientFactory.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/networking/CustomSSLGlideModule.java
> Support custom SSL certificates for covers loaded using Glide

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WebOpacNet.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/i18n/StringProvider.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/WebOpacNetAccountTest.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/WebOpacNetTest.java
- opacclient/libopac/src/test/resources/webopac.net/account.json
- opacclient/libopac/src/test/resources/webopac.net/cancel_success.json
- opacclient/libopac/src/test/resources/webopac.net/prolong_all_impossible.json
- opacclient/libopac/src/test/resources/webopac.net/prolong_all_partial_success.json
- opacclient/libopac/src/test/resources/webopac.net/prolong_all_possible.json
- opacclient/libopac/src/test/resources/webopac.net/prolong_fee.json
- opacclient/libopac/src/test/resources/webopac.net/prolong_impossible.json
- opacclient/libopac/src/test/resources/webopac.net/prolong_possible.json
- opacclient/libopac/src/test/resources/webopac.net/prolong_success.json
- opacclient/libopac/src/test/resources/webopac.net/reservation_fee.json
- opacclient/libopac/src/test/resources/webopac.net/reservation_success.json
- opacclient/opacapp/src/main/res/values-de/strings_api_errors.xml
- opacclient/opacapp/src/main/res/values/strings_api_errors.xml
> Account support for winmedio.net

- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountFragment.java
- opacclient/opacapp/src/main/res/values-de/strings.xml
- opacclient/opacapp/src/main/res/values/strings.xml
maybe this can help us to get some people to contribute to this open source project 😉
> Improve the "not supported" message for some APIs

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/VuFind.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/i18n/StringProvider.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/VuFindAccountTest.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/VuFindSearchTest.java
- opacclient/libopac/src/test/resources/vufind/medialist/kreisre.html
- opacclient/libopac/src/test/resources/vufind/reslist/kreisre.html
- opacclient/libopac/src/test/resources/vufind/result_detail/kreisre_copies.html
- opacclient/libopac/src/test/resources/vufind/result_detail/kreisre_copies_desc.html
- opacclient/libopac/src/test/resources/vufind/result_detail/kreisre_volumes.html
- opacclient/libopac/src/test/resources/vufind/result_detail/kreisre_volumes_desc.html
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/networking/CoverDownloadTask.java
- opacclient/opacapp/src/main/res/values-de/strings_api_errors.xml
- opacclient/opacapp/src/main/res/values/strings_api_errors.xml
This adjusts the existing VuFind API to be also compatible with [smartBib](https://www.subkom.de/smartbib/), a VuFind variant by subkom. It also implements all account features for smartBib. They were tested using the new OPAC of Recklinghausen county libraries at https://www.bib-kreisre.de/.
> smartBib (VuFind variant): Search and account support

- opacclient/libopac/build.gradle
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/OpacApiFactory.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/NetBiblio.kt
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/i18n/StringProvider.java
- opacclient/libopac/src/main/resources/meanings/general.json
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/NetBiblioTest.kt
- opacclient/libopac/src/test/resources/netbiblio/lent/basel.html
- opacclient/libopac/src/test/resources/netbiblio/reservations/basel.html
- opacclient/libopac/src/test/resources/netbiblio/reservations/basel_empty.html
- opacclient/opacapp/src/main/res/values-de/strings_api_errors.xml
- opacclient/opacapp/src/main/res/values/strings_api_errors.xml
This implements support for the NetBiblio library system, used for example in [Basel](https://katalog.stadtbibliothekbasel.ch/GGG/WebOPAC)
> implement support for NetBiblio

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Adis.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/MultiStepResultHelper.java
* fixes umlaute in status message
* fixes reservation dialog in Munich Gasteig Bib
Addresses: #560
https://github.com/opacapp/opacclient/issues/560
> [BUGFIX] fix reservation for Munich Gasteig

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/objects/SearchResult.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/OpacClient.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/ResultsAdapter.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailActivity.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultListActivity.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultListFragment.java
- opacclient/opacapp/src/main/res/layout/fragment_searchresult_list.xml
- opacclient/opacapp/src/main/res/layout/listitem_searchresult.xml
- opacclient/opacapp/src/main/res/values/strings.xml
- opacclient/opacapp/src/main/res/values/styles_opacapp.xml
The goal of this commit is to support multi-library search in the plus app.
It was care taken to allow backwards compatibility and all introduced changes have no effect on existing usecases.
> Adding base architecture for multi library search

- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/ResultsAdapter.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/webservice/WebService.java
Added api endpoint for fetching library group configs.
> Added api endpoint for group configs

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SISIS.java
- opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SISISTest.java
- opacclient/libopac/src/test/resources/sisis/medialist/Dresden-renew_all.html
For journal items, the title is empty and the journal name and issue is in the signature field. This is similar to issue #516 / commit 164ebe350a6db07e6.  
Left = before this PR   &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp; right = with this PR (compare items 3, 4 and 6):
> SISIS: Fix prolongAllResult for journal items

- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/OpacClient.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchFragment.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailActivity.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultListActivity.java
- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultListFragment.java
- opacclient/opacapp/src/main/res/drawable/recyclerview_divider.xml
- opacclient/opacapp/src/main/res/values-de/strings.xml
- opacclient/opacapp/src/main/res/values/colors.xml
- opacclient/opacapp/src/main/res/values/strings.xml
Added more support for Meta Search / Multi library search
> More support for Meta Search

- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java
Removed logs that are not needed anymore.
> Removing logs

- opacclient/opacapp/build.gradle
> Removed unneeded dependency

- opacclient/opacapp/src/main/res/layout/navigation_drawer_header.xml
Changed XML to pass lint checks.
> Fixed xml for lint check

- opacclient/opacapp/src/main/res/menu/navigation_drawer.xml
Added navigation drawer item for meta search in plus version.
> Added navigation drawer item for meta search in plus version

- opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchFragment.java
This PR aims on adding support that Fragments which extend SearchFragment can provide their own layout xml file.
> Adding support for different layout in plus app

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Adis.java
[HfM Karlsruhe](https://bsz.ibs-bw.de/aDISWeb/app?service=direct/0/Home/%24DirectLink&sp=SOPAC33) seems to have gotten an update of Adis, which made some adjustments in the API for the account view and search necessary.
Also, they added a free search field that is accessible in the advanced search screen (and can be combined with the advanced fields), so I also implemented support for that.
> Fixes and improvements for Adis at HfM Karlsruhe

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/OpacApiFactory.java
- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Lissy.kt
> Implement LISSY

- opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Adis.java
Several improvements to the Adis media list:
- Support for media type prefixes
- Only extract author by splitting at slash if the title string actually contains a slash (and not another part of the item like the signature)
- When extracting the author by splitting the title at a colon, do not use the whole string as author if the title does not contain a colon
> Adis: media/reservation list improvements
