opacapp/opacclient

opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountFragment.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java

This fixes the following (quite critical) bugs:
- NoSuchMethodError on API < 17 for `RelativeLayout.LayoutParams.removeRule()` (strangely, Android Studio didn't warn me about this). This prevented opening SearchResultDetailFragment on those devices.
- ClassCastException for all the StepTasks (Prolong, Cancel, Prolong All, etc.). This prevented running those tasks. I currently cannot test if it works now, could you test it by prolonging something?
Maybe we should do a quick bugfix update.

Fix two bugs

---

opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultListActivity.java

It seems like Android sometimes needs even smaller images to be able to put them into a Bundle.

Make images put into parcelable even smaller

---

opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/LibraryListActivity.java

I still don't understand why Android Studio didn't warn me about this.

Remove another method call only working on API >= 17

---

opacclient/.idea/inspectionProfiles/Project_Default.xml
opacclient/opacapp/build.gradle
opacclient/opacapp/proguard-rules.txt
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java

We need to repackage android.support.v7 classes using ProGuard because some devices include an old version of the support library (normally they shouldn't include the support library at all), which causes a `java.lang.NoClassDefFoundError`.
See also: https://code.google.com/p/android/issues/detail?id=78377

Fix Bug on Samsung devices with Android 4.2

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/TestApi.java
opacclient/opacapp/src/main/assets/bibs/Test.json
opacclient/opacapp/src/main/res/layout-w720dp/fragment_account.xml
opacclient/opacapp/src/main/res/layout/fragment_account.xml

A crash was caused when going from SearchFragment to AccountFragment when the list of lent and reserved items was taller than a certain amount (depending on the device's GPU, typically 4096 pixels). To reproduce the bug, I implemented the `account()` function of the `TestApi` to create a very long list (it needed to be 16384 pixels tall in the emulator).
As we received a number of crash reports (and a negative review in the Play Store) concerning this bug, this could maybe justify a bugfix release.

Fix crash in AccountFragment

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/IOpac.java

More fixes for iOPAC 1.45:
- non-prolongable media should be recognized properly (not tested)
- support for new sharing URLs that lead to the full frameset of the OPAC, not only the detail page
and for all iOPAC versions
- fix cancelling reservations for when "kndnr" is not equal to the login number (for whatever reason)
- error message when reserving media that is already lent
- improve detecting the status in the result list

iOPAC improvements

---

opacclient/opacapp/src/main/assets/bibs/Offenburg.json

Hallo Raphael
Offenburg Stadtbibliothek funktioniert nicht mehr. Die haben ihr BiBer system aktualisiert. Habe nun Offenburg.json aktualisiert und getestet. 
Viele Grüße
Rüdiger

Offenburg Stadtbibliothek: Fix nach OPAC-Systemupdate der Bibliothek

---

opacclient/opacapp/src/main/assets/bibs/Greifswald_Uni.json
opacclient/opacapp/src/main/assets/bibs/Stralsund_FH.json
opacclient/opacapp/src/main/assets/bibs/Weimar_Uni.json

I found that Greifswald_Uni, Stralsung_FH and Weimar_Uni also use LBS and activated account support for them. This was not tested.

Account support for 3 more libraries using LBS

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/PicaLBS.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/PicaOld.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/i18n/StringProvider.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/storage/AccountDatabase.java
opacclient/opacapp/src/main/res/layout/listitem_account_lent.xml
opacclient/opacapp/src/main/res/layout/listitem_account_reservation.xml
opacclient/opacapp/src/main/res/values-de/strings_api_errors.xml
opacclient/opacapp/src/main/res/values/strings_api_errors.xml

Issues were reported with our new Pica LBS implementation (including the same media name being displayed for all the lent media). This is fixed here. In addition, I enabled the status in the account view to be able to take up multiple lines (this can happen when error messages like "too many renewals" or "this volume has a reservation" need to be displayed there in addition to the return/reservation date).

Fixes and improvements for Pica LBS

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Adis.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/BiBer1992.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Bibliotheca.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Heidi.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/IOpac.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Pica.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Primo.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SISIS.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/TouchPoint.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/VuFind.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WebOpacNet.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WinBiap.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Zones22.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/searchfields/DropdownSearchField.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/searchfields/SearchField.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/OpacActivity.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchFragment.java

This allows a more comprehensible and compact usage of the
DropdownSearchField. In addition, due to replacing many HashMap
instances by the simpler DropdownSearchField.Option object, the memory
footprint will be reduced.
After applying #337, the class `WebOpacAt` needs to be adapted …

Introduce DropdownSearchField.Option

---

opacclient/libopac/build.gradle
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/PicaOld.java
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/BaseTest.java
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/PicaOldTest.java
opacclient/libopac/src/test/resources/pica_old/medialist/marburg.html
opacclient/libopac/src/test/resources/pica_old/reslist/marburg.html

The list of reservations was not parsed correctly.
I also created a `PicaOldTest` for `parseMediaList` and `parseResList` that uses HTML files of the account view we received from a bug reporter (with anonymized user data and changed book titles, signatures and IDs)

Fix bug in PicaOld account view

---

opacclient/opacapp/src/main/assets/bibs/Schramberg.json

Due to a typo during reconfiguration of Schramberg's `accounttable`, it still was not working.

Fix Schramberg again

---

opacclient/build.gradle
opacclient/opacapp/build.gradle
opacclient/opacapp/proguard-rules.txt

We need to check if this ProGuard configuration fixes the problem on Wiko devices running Android 4.2.

Re-enable ProGuard and update dependencies

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WinBiap.java
opacclient/libopac/src/test/resources/winbiap/reslist/guetersloh.html

WinBiap 4.3 (used for example in Gütersloh) uses a slightly different account page. We now also got a HTML sample of the list of reserved media from a user in Gütersloh.

Implement parseResList for new version of WinBiap

---

opacclient/build.gradle

* Maven Central and oss.sonatype are not needed for the dependencies we use.
* The multilinecollapsingtoolbar library is now available on JCenter.

Remove unneeded Maven repositories

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/IOpac.java

In Glückstadt, mtyp.js is not in the "iopac" directory

IOpac: getSearchFields media types fix

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WinBiap.java

In WinBiap 4.4, the "ct100" at the beginning of the field IDs has disappeared.

Fix mediagroup and branch selection for WinBiap 4.4

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/WinBiap.java
opacclient/opacapp/src/main/assets/bibs/Baden.json
opacclient/opacapp/src/main/assets/bibs/Buchholz_Nordheide.json
opacclient/opacapp/src/main/assets/bibs/Muenchen_Vaterunserkirche.json
opacclient/opacapp/src/main/assets/bibs/Ravensburg_DHBW.json
opacclient/opacapp/src/main/assets/bibs/Schwaig.json
opacclient/opacapp/src/main/assets/bibs/Trier.json
opacclient/opacapp/src/main/assets/bibs/Wettingen.json

* Prolonging fixed for WinBiap 4.4 (tested in Memmingen)
* Getting cancelurl fixed for WinBiap 4.4 (tested using HTML sample, cancelling reservations itself not tested)
* New server for Baden and Wettingen
* Trier switched to OPEN
* Added libraries
For the first fix, I copied some code (essentially a RegEx) from the OPEN API implementation because both systems use Microsoft's ASP.NET framework and its "__doPostBack" Javascript mechanism. Should we instead transfer this code to a new function and place it in `BaseApi` or a new utility class?

WinBiap 4.4 and other fixes, new libraries

---

README.md
opacclient/libopac/README.md

We should maybe merge this with the next release so that we have some documentation about `libopac` being available as a separate library.

Add README file for libopac

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Adis.java

The limit in string.split() introduced by commit
8dfbc947d19c960b4200ec88f555ee187962a540
triggers an array out of bounds exception. Also since we want the second
result, the limit is wrong anyway. The date given has the form
(DD.MM.YYYY - DD.MM.YYYY) with the start and end date of the lending
period. For the account listing the second date is the relevant one.

Fix off-by-one for Nuremberg fix.

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/TouchPoint.java

One part of the bug was that the reservation() function tried to guess whether a login was needed or not based on the Session lifetime, which did not work every time. The easiest way to fix this was to just login every time, which does not seem to be harmful if already logged in (other than causing the reservation to take a fraction of a second longer).
Additionally, a parameter called "submited" [sic!] seems to have been added to the reservation form that was missing from our code.

TouchPoint: Fix reservation bug

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/BiBer1992.java
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/BiBer1992AccountTest.java
opacclient/libopac/src/test/resources/biber1992/medialist/erkrath_opac.html
opacclient/libopac/src/test/resources/biber1992/medialist/erkrath_opax.html
opacclient/libopac/src/test/resources/biber1992/medialist/nuertingen.html
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/OpacClient.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountEditActivity.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountFragment.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountListActivity.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/DrawerAccountsAdapter.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/LibraryListActivity.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/MainActivity.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/MainPreferenceFragment.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/OpacActivity.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultListFragment.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SnoozeDatePickerActivity.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/reminder/ReminderBroadcastReceiver.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/reminder/ReminderHelper.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/reminder/SyncAccountService.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/storage/AccountDataSource.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/storage/AccountDatabase.java

To avoid `DatabaseLockedException`, I changed `AccountDatabase` so that there is only one instance of it created. According to multiple sources, e.g.
http://stackoverflow.com/questions/4547461/closing-the-database-in-a-contentprovider/12715032#12715032 and
http://touchlabblog.tumblr.com/post/24474750219/single-sqlite-connection
we can then omit calling `close()` on the database instead of having to count the number of concurrent accesses to make sure we don't close the DB while a thread is still using it.

Singleton for SQLite database, support detail links for old BiBer OPACs, add BiBer Test HTML

---

.travis.yml
README.md
opacclient/build.gradle
opacclient/libopac/build.gradle
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Bibliotheca.java
opacclient/opacapp/build.gradle
opacclient/opacapp/src/debug/java/de/geeksfactory/opacclient/utils/DebugTools.java

- Fixed search using Bibliotheca not working the first time when the sorting field was used
- Added test coverage report for libopac tests, will be uploaded to https://coveralls.io/ using Travis CI. #434 also adds these reports for the reminder unit tests.
- Added "Leak Canary" library for debug builds (currently detects no leaks)

Bibliotheca fix, Test coverage, Leak Canary

---

opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/OpacClient.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/LibraryListActivity.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/MainPreferenceFragment.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/adapter/AccountAdapter.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/adapter/ReservationsAdapter.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/reminder/SyncAccountService.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/storage/PreferenceDataSource.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/webservice/LibraryConfigUpdateService.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/webservice/UpdateHandler.java
opacclient/opacapp/src/main/res/values-de/strings.xml
opacclient/opacapp/src/main/res/values/strings.xml

In release builds this situation normally should not appear (but it currently does with F-Droid builds, see #457). But this is also helpful for making debug builds possible without running `downloadJson` first.

Don't crash when last_library_config_update.txt is missing from the APK

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Bibliotheca.java
opacclient/libopac/src/main/resources/meanings/general.json

Bibliotheca libraries (at least some of them, e.g. Bielefeld and Mannheim) have a search field called "Titel" combined with two radio buttons that allow you to select either "Stichwörter" or "Titelanfang". Until now, we only supported "Stichwörter".
A user requested that we should also have a real title seach field. So with this PR, a field is added that allows you to use "Titelanfang".
@raphaelm, you are probably more familiar with Bibliotheca. Do you think this will break anything? I tested it in Bielefeld and it seems to work there.

Bibliotheca: Add title search field

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Adis.java

@raphaelm: As requested earlier today, this change fills the item id field in AccountData with the 14 digit library id, parsed from the title in the html. Works for the Stadtbibliothek München.

Add id retrieval for Stadtbibliothek München in Adis

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Adis.java

Stadtbibliothek Stuttgart now switched from their previous OPAC (Bibliotheca 2.4), which we didn't support, to aDIS.
https://opac.sbs.stuttgart.de/aDISWeb/app?service=direct/0/Home/$DirectLink&sp=SOPAC
There were a few problems that lead to our API not being able to load the advanced search form (and therefore to parse the search fields) in this aDIS instance. I don't really understand why they use the "&sp=" parameter twice (with different values) in their URLs, but it seems to be necessary to get the right response. I'm not that familiar with the aDIS API, so it might be quite a "quick-and-dirty" fix 😉 
Account features could not be tested, just that entering wrong credentials correctly results in an error message.
One search field that is still not shown in the app is the "Sie suchen …

Adis: fixes for Stuttgart

---

opacclient/libopac/build.gradle
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/OkHttpBaseApi.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Open.java
opacclient/opacapp/build.gradle
opacclient/opacapp/proguard-rules.txt

With this, we can wait for the requests we actually need instead of all requests that are currently executed by OkHttp (which might happen if something is called concurrently).
this also makes libopac depend on Java 8
Still, we need to use the [streamsupport](https://sourceforge.net/projects/streamsupport/) library to be compatible with Android - the Android build system does backport lambdas, but not CompletableFutures and the stream API.

OkHttpBaseApi: Replace our hacky asyncWait implementation with CompletableFutures

---

opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/ResultsAdapter.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/storage/PreferenceDataSource.java
opacclient/opacapp/src/main/res/xml/settings.xml

Fixes #502 
As explained in the commit message:
```
There is no option to disable loading of covers while mobile data is switched on.
This is counterproductive for users who would prefer less data to be used when on a metered network.
As such, let's add an option to disable loading of covers while on mobile data.
```

Add option to disable loading of covers on mobile data

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SISIS.java
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SISISAccountTest.java
opacclient/libopac/src/test/resources/sisis/medialist/erfurt.html

A user from Erfurt reported that a few lent items appeared more than once in the account view. I suspect the reason for this is that the app may load the second page more than once because there are multiple links pointing to it (link to page 2, link to the next page, link to the last page). I changed the code so that the links are saved in a HashMap, so a link cannot appear more than once. The result is checked with a unit test, but I couldn't test it in the app with a real account because none of our working SISIS test accounts has more than 10 lent items (actually, none of them has *any* lent items).

Fix, test and refactoring for handling SISIS account pages

---

.gitignore
opacclient/opacapp/build.gradle
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/OpacClient.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/LibraryListActivity.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/reminder/SyncAccountJob.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/utils/ErrorReporter.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/webservice/LibraryConfigUpdateService.java

We had some problems with ACRA before, the version we currently use doesn't work for Android 8.0+, and we already use Sentry for other projects, so this PR implements the switch.
To make Sentry work, we additionally need to add a file named `sentry.properties` in `opacclient/opacapp/src/main/resources` with the content:
```
dsn=<insert DSN from Sentry here>
```
I haven't added this file to the Git repository to keep our DSN secret. If the file is not present, that's no problem, Sentry will just not send any reports (which it won't do in debug builds anyway).
Maybe we should document that the file needs to be present somewhere (I just don't know where) or even create some Gradle task that ensures that it is there when a release build is compiled, so that we don't forget it.
Currently, in …

Switch from ACRA to Sentry

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SISIS.java
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SISISTest.java
opacclient/libopac/src/test/resources/sisis/medialist/erfurt_page2.html
opacclient/libopac/src/test/resources/sisis/medialist/erfurt_page3.html

When more than 30 items are lent (or, presumably, reserved) in a SISIS OPAC, the link to the fourth page of items (10 items per page) is not visible from the first page. This changes the implementation so that each page is checked for links to previously unseen pages instead of only going to all links visible on the first page.

SISIS: fix problem when more than 30 items are lent

---

opacclient/opacapp/src/main/res/layout/navigation_drawer_header.xml
opacclient/opacapp/src/main/res/values/dimens.xml

Fixed icon size in relation to the space left and adjusted the top drawer height. No overlapping of the icon should occur in landscape mode anymore.

Fix icon misaligned in landscape mode

---

opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/ResultsAdapter.java
opacclient/opacapp/src/main/res/drawable/status_light_green_check.xml
opacclient/opacapp/src/main/res/drawable/status_light_red_cross.xml
opacclient/opacapp/src/main/res/drawable/status_light_yellow_alert.xml
opacclient/opacapp/src/main/res/layout/listitem_searchresult.xml

Changed the status icons to make it more visible for color blind people. Adjusted also the size of the status indicators. The same colors were used as the one before.

Make status indicator circles accessible for color-blind people

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/objects/AccountItem.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/adapter/AccountAdapter.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/adapter/LentAdapter.java
opacclient/opacapp/src/main/res/layout/listitem_account_item.xml

Make items of lent items list look a bit nicer and clearer:
- Remove trailing delimiter for items without author (author string is empty but not null) (see second item in example below)
- Change title/author delimiter from ‘,’ to ‘.’ and print title in bold for better readability and clarity (see e.g. third item where is wasn't particularly clear where the title ends and the author starts)
- Remove details about person after ¬ sign (at least Dresden municipal library often has further information such as author, editor, producer etc. after the person's name) (see first and last item)
Add branch information to the list. I regularly borrow books from different branches of the same library. When I need to return a book I want to see what other books I hold from the same branch. This was only …

Improve lent item list format and add branch

---

opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/reminder/ReminderBroadcastReceiver.java
opacclient/opacapp/src/main/res/values-cs/strings.xml
opacclient/opacapp/src/main/res/values-de/strings.xml
opacclient/opacapp/src/main/res/values-el/strings.xml
opacclient/opacapp/src/main/res/values-es/strings.xml
opacclient/opacapp/src/main/res/values-fr/strings.xml
opacclient/opacapp/src/main/res/values-it/strings.xml
opacclient/opacapp/src/main/res/values-ja/strings.xml
opacclient/opacapp/src/main/res/values-pl/strings.xml
opacclient/opacapp/src/main/res/values-tr/strings.xml
opacclient/opacapp/src/main/res/values/strings.xml

Just a small beautification.
Add singular forms to avoid texts like "1 items have expired". Change de, es, fr, it, ja and pl translations accordingly. Change and complete cs translation accordingly. Change incomplete translations for el and tr (to the best of my knowledge, as I don't know these languages).

Singular forms for expired items notification

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Adis.java
opacclient/libopac/src/main/resources/meanings/general.json

Hallo Raphael,
die Stadtbücherei in Stuttgart hat vor kurzem ihre Suchseiten etwas überarbeitet. Dies hatte zur Folge, dass
1. der "_Suchbereich_" als BRANCH erst bei den "Show more search fields" auftauchte
2. die Detailanzeige bei nur einem Treffer nicht funktioniert hat.
Bei 2. hat der mit _Reset_ kommentierte Code wg. geänderter Toolbar-Nummer nicht funktioniert und man hat eine SingleResultFound/NotReachableException bekommen.
Hier mein Vorschlag die Probleme zu fixen. Erfolgreich getestet habe ich neben Stuttgart noch die Suche in Nürnberg und München.
Grüße aus Stuttgart - Michael

Fix Adis Stuttgart 2018-12

---

opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/ResultsAdapter.java

This ensures **consistency in display between lent items list and search results list**. In the former (listitem_account_item.xml), there are individual image views for cover images and icons of size 56 and 40 dp, respectively, which are shown/hidden as needed. In the search results list, both covers and icons are displayed using the same 56 dp image view, which results in disproportionately big icons as compared to cover images. This is especially striking when book icons (landscape format) are mixed with cover images (usually portrait format).
Instead of introducing separate image views for covers and icons as in the lent items list, we just set a padding of 8 dp in case of icons being displayed in the ivType image view to shrink them to 40 dp. As the conversion from dp to px is a …

Shrink icon size in search results to 40 dp

---

.gitlab-ci.yml
.travis.yml
opacclient/build.gradle
opacclient/opacapp/build.gradle
opacclient/opacapp/src/foss/java/de/geeksfactory/opacclient/utils/GooglePlayTools.java
opacclient/opacapp/src/googlePlayServices/java/de/geeksfactory/opacclient/utils/GooglePlayTools.java
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/OpacClient.java

so that we can use up-to-date TLS versions and cipher suites on older Android devices, provided that they have a recent version Google Play Services installed (otherwise, the app will ignore it and use the system default security provider - no error message is shown).
This introduces two build flavors ("foss" and "googlePlayServices") to the app, which means we need to update our scripts to generate release builds for Google Play (@raphaelm ?) as well as F-Droid.

Use Google Play Services Security provider

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Adis.java

With this, I basically reverted commit 7ed3616. I don't see what scrolling problem was fixed with 7ed3616, because as far as I can see, scrolling (and going to detail pages in random order) still works correctly. Tested in Musikhochschule Karlsruhe and Stadtbibliothek München.

Fix detail view in Musikhochschule Karlsruhe

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/objects/DetailedItem.java

so that volumes has a setter and getter for the whole list the same way as copies has.
I came across the missing setter in `slub.kt` where I get the volumes list by mapping `Volumes()` onto a JSON array and it's therefore more idiomatic to set the whole list I get this way as opposed to adding all the elements to the list.

Add missing setVolumes and fix typos

---

.editorconfig

This will make the codestyle consistent throughout the project.
(This removes unused imports as a side effect, but that should be fine.)
No actual code changes were made, as this was done automatically by Android Studio.

Adjust codestyle to an .editorconfig

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/utils/KotlinUtils.kt

The rangeTo operator ".." includes the end element which leads to an array index
out of range error. The "until" function does not include the end element.
see https://kotlinlang.org/docs/reference/ranges.html

Fix array index range of JSONArray extension functions

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/OkHttpBaseApi.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SLUB.kt
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SLUBTest.kt

This resolves items 3 and 4 of #595.

SLUB: Get Results by Id for Lent and Reserved Items

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SISIS.java
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SISISTest.java

In Dresden, they changed the URL in the AJAX section: it now starts with "/webOPACClient/", which is also part of the opac_url.
OLD: `"jsp/result..." ` (used for instance in Erfurt)
NEW: `"/webOPACClient/jsp/result..."` (used in Dresden)
So we retrieve just the part starting with `"jsp/result..."`
Eliminate duplicate definition of the regex in `parse_search` and `loadDetail.`

SISIS: fix regex for cover URL for Dresden Städtische Bibliotheken

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SLUB.kt
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SLUBTest.kt
opacclient/libopac/src/test/resources/slub/account/account.json

The title in the json obtained from the API may contain ¬ signs which are not
shown in the web catalog. These signs are removed for better readability.
**Current display in opacapp:**
**Current display on library web page:**
**Fixed display in opacapp:**
(we leave ¬ signs in the contributor field as they are used, when followed by a bracket [, to cut off the contributor's role in the list view, see f16534969939)

SLUB: Fix titles in account view (loans and reservations)

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SLUB.kt

There is no specific media type for `"Norm"` (norms or standards). As these are mostly electronic resources (at least the current norms) I mapped them to the media type `EDOC`. Or do we need a new, more specific mediatype for it?

SLUB: add some more media types

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SLUB.kt
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SLUBTest.kt
opacclient/libopac/src/test/resources/slub/search/simple-item.json

Sublocation names (stored in the `department` field) can contain HTML escape entities, e.g. _"Ausgabe \&uuml;ber Ausleihtheke"_ or _"Au\&szlig;enmagazin"_. These are now resolved regular characters.

SLUB: resolve html escapes in sublocation

---

.gitignore
tools/add_library.py

Since mid 2018 you need an API key to use the Google maps API. If you have such a key,
store it in a file `googlemaps_api_key.txt` in the same directory as `add_library.py`
(this file is not checked into version control).
If you don't have a Google API key, we use OSM Nominatim instead (no key required).

TOOLS: Fix loadGeoPossibilities

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/BaseApi.java
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/ApacheBaseApiTest.java

cleanUrl replaces missing values in key-value-pairs with an empty string so that
?param&... becomes ?param=&... . This may lead to problems in some cases (e.g.
at SLUBApi when resolving libero references in getDetailById). Even it we'd
replace the "" by null in the else branch of the current implementation, a
trailing = will still be be added by URLEncodedUtils.format, as Android uses
httpclient-android version 4.3.5.1 which has a bug to add a trailing = sign
to key-only parameters by replacing missing parameters with empty strings the
same way clearUrl does (versions 4.5 and newer work correctly but can't be
used by Android, see also https://hc.apache.org/httpcomponents-client-4.5.x/android.html.
To avoid this we make cleanUrl non-static so that APIs can overwrite
it with their own …

Make cleanUrl non-static so that APIs can overwrite it

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/OkHttpBaseApi.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SLUB.kt
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SLUBTest.kt
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultDetailFragment.java
opacclient/opacapp/src/main/res/layout/listitem_volume.xml

This is a workaround as the only possibility to add links to other detailed
items from a detailed item. It's possible as we can display volumes and
copies at the same time. References are some kind of details which is why
the display order of copies and volumes was swapped: first show volumes
(which may be references) right after the details and only then copies.
Increase volumes text view to maximum two lines high to be able to put
the title of the reference and the reference itself on different lines
for better readability.
Change resolution of bc or rsn and the new libero identifiers to following
head redirects and retrieving the final url to get the id identifier. This
requires one request more than the old method (get location parameter from
non-redirecting head request) but is much …

SLUB: Add references to other SLUB catalog items as volumes

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SLUB.kt
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/objects/Copy.java
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SLUBTest.kt
opacclient/opacapp/build.gradle
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/CopiesAdapter.java
opacclient/opacapp/src/test/java/de/geeksfactory/opacclient/frontend/CopiesAdapterTest.java

Use same colored status markers as in search result list view to show availability status of individual copies in search result details:  
See #606 for discussions.

 Provide status code for copies and show colored status markers

---

opacclient/opacapp/build.gradle

Searchresult detail fragment didn't scroll to end after device rotation. This was fixed by
https://github.com/material-components/material-components-android/commit/a21a30026a33fc20cf7ad699d32d1298b84096c6
in [release 1.3.0-alpha04](https://github.com/material-components/material-components-android/releases/tag/1.3.0-alpha04) of material components.
This resolves #605.

Fix scrolling issue

---

opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/SearchResultListActivity.java

META_SEARCH_FLAG was only passed if a search result had a cover image.
This led to issues for search results without a cover.

Fixed issue META_SEARCH_FLAG was only passed on if search result had cover

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SLUB.kt
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/i18n/StringProvider.java
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SLUBTest.kt
opacclient/opacapp/src/main/java/de/geeksfactory/opacclient/frontend/AccountFragment.java
opacclient/opacapp/src/main/res/values-de/strings_api_errors.xml
opacclient/opacapp/src/main/res/values/strings_api_errors.xml

This also fixes (second commit) a small bug that prevented account data update after a successful renewal without results list:
**Refresh data after prolongAll or prolongMultiple without results list**
prolongAll and prolongMultiple return a ProlongAllResult object that may or may not
contain a list of the individual success values. Some APIs (e.g. Koha or SLUB) don't
populate this results list (ProlongAllResult.results == null) and only provide a
general message (MultistepResult.message). In this case the account information was
not updated after a successful renewal. This PR forces data update after a successful
renewal even if the results list is null.

SLUB: Implementation of prolongMultiple

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Arena.kt
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Koha.kt
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/NetBiblio.kt

it was introduced in 99812b4d40328f33f5c5992ad0f9e67ea1cb99b3 by mistake (sorry for this).

Fix double return statement

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SLUB.kt
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SLUBTest.kt
opacclient/libopac/src/test/resources/slub/search/detail-with-cover-html-swbplus.json
opacclient/libopac/src/test/resources/slub/search/detaill-cover-jpg-as-material.json
opacclient/libopac/src/test/resources/slub/search/simple-item.json

Set cover image uris for detailed items from links. With SLUB, many covers come from [SWBPlus](http://swbplus.bsz-bw.de/) where the htm file contains a cover image with the same name but ".jpg" extension.

SLUB: get cover image uris

---

opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SISISTest.java
opacclient/libopac/src/test/java/de/geeksfactory/opacclient/apis/SLUBTest.kt

The update of Mockito from `1.10.19` to `3.8.0` in 11833f32344ac broke a number of tests, see #638. I fixed the tests for the APIs I use (SLUB and SISIS).  
The are still failing test in BiBer1992AccountTest, BibliothecaAccountTest and VuFindAccountTest but I'm not familiar with these APIs so I didn't try to fix the failing tests. These failures seem to be related to the `jsoup` update, see #584.

Fix broken SLUB and SISIS Tests after Mockito update

---

opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/OkHttpBaseApi.java
opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/SISIS.java

Since Nov 23, the server doesn't return any lent items unless you include an `Accept-Language` header, whereby it doesn't matter what language you specify.
Also, calling `start` in SISIS's `account` function is indeed necessary at least for Dresden, so the TODO was removed.
Closes #657.

Fix SISIS for Städtische Bibliotheken Dresden
